name: Publish Wiki
on:
  push:
    branches: [master]
    paths:
      - Wiki/**
  workflow_dispatch:
  gollum:
concurrency:
  group: Publish Wiki
  cancel-in-progress: true
permissions:
  contents: write
env:
  GIT_AUTHOR_NAME: Wiki Gustav[bot]
  GIT_AUTHOR_EMAIL: actions@github.com
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checking out the repository
        uses: actions/checkout@main
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Placeholder processing the wiki
        uses: richardrigutins/replace-in-files@main
        with:
          files: Wiki/*.md
          search-text: '{{ GITHUB_REPO }}'
          replacement-text: '${{ github.server_url }}/${{ github.repository }}'
#     - name: Spellchecking the Wiki
#       uses: rojopolis/spellcheck-github-actions@master
#       with:
#         source_files: Wiki/*.md
#         task_name: Markdown
#         ignores:
#           - code
#           - pre
      - name: Syncing the Wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: Wiki/
          destination: wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
  pull-wiki:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checking out the repository
        uses: actions/checkout@main
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Syncing the Wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: Wiki/
          token: ${{ secrets.GITHUB_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: master
